### ISSUE TITLE
Store window position on close

### ISSUE THREAD

**Issue by ghost** [idesis-gmbh/BareBrowser#20]
It would be nice, if the bare browser would save the last window/screen position before it has been closed and opens at the same position again, after it has been started again.

**Use Case:** A user works in a multi monitor/screen environment. He/she wants to close the bare browser and keep working at the exact position it has been closed after restart.

**Comment by mn4367** [comment]
Implemented in ff6f633 and released with [Version 3.0.0](https://github.com/idesis-gmbh/BareBrowser/releases/tag/v3.0.0).

*Note:* due to backward compatibility reasons this feature is off by default. It can be turned on by setting `Window.LastWindowPosition.Restore` to `true`; please see also the configuration section in the docs.
